plugins:
  - jekyll-remote-theme
theme: jekyll-theme-slate
#remote_theme: vszhub/not-pure-poole

# Setup
title: Kenneth V.
description: Personal Blog & Website for CSE 15L
image: /background2.jpg
#url:
#avatar: 
#paginate:
#cover_image:
