plugins:
  - jekyll-remote-theme
theme: jekyll-theme-slate
#remote_theme: vszhub/not-pure-poole

# Setup
title: [Kenneth V.](https://kennethkietvuong.github.io/cse15l-lab-reports/)
description: Personal Blog & Website for CSE 15L
#url:
#avatar: 
#paginate:
#cover_image:
